django_blog_program/django_blog_program/urls.py
from django.contrib import admin
from django.contrib.sitemaps import views as sitemap_views
from django.urls import path, re_path

from blog.rss import LatestPostFeed
from blog.sitemap import PostSiteMap
from blog.views import post_list, post_detail, PostDetailView, IndexView, CategoryView, TagView, SearchView
from comment.views import CommentView
from config.views import LinkListView
from django_blog_program.custom_site import custom_site

urlpatterns = [
    path('admin/', custom_site.urls),
    path('super-admin/', admin.site.urls),

    #path("", post_list, name="post_list"),
    #re_path('category/(?P<category_id>\d+)/$', post_list, name="post_list"),
    #re_path('tag/(?P<tag_id>\d+)/$', post_list, name="post_list"),
    # re_path('post/(?P<post_id>\d+)/$', post_detail, name="post_detail"),
    # re_path('links/$', links, name="post_detail"),


    path("", IndexView.as_view(), name="post_list"),
    re_path('category/(?P<category_id>\d+)/$', CategoryView.as_view(), name="post_list"),
    re_path('tag/(?P<tag_id>\d+)/$', TagView.as_view(), name="post_list"),
    re_path('post/(?P<post_id>\d+)/', PostDetailView.as_view(), name="post_detail"),
    re_path('search/', SearchView.as_view(), name="post_list"),
    re_path('links/', LinkListView.as_view(), name="links"),
    re_path('comment/', CommentView.as_view(), name="comments"),
    re_path('^rss|feed/', LatestPostFeed(), name="rss"),
    re_path('^sitemap\.xml/$', sitemap_views.sitemap, {'sitemaps': {'posts': PostSiteMap}}, name="comments"),
]

django_blog_program/comment/models.py
from django.db import models

from blog.models import Post


# Create your models here.


class Comment(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )
    # target = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='评论目标')
    target = models.CharField(max_length=100, verbose_name='评论目标')
    content = models.CharField(max_length=2000, verbose_name='内容')
    nickname = models.CharField(max_length=50, verbose_name='昵称')
    website = models.URLField(verbose_name='网站')
    email = models.EmailField(verbose_name='邮箱')
    status = models.PositiveIntegerField(default=STATUS_NORMAL, choices=STATUS_ITEMS, verbose_name='状态')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    class Meta:
        verbose_name = verbose_name_plural = '评论'

    def __str__(self):
        return self.nickname

    @classmethod
    def get_by_target(cls, target):
        return cls.objects.filter(status=cls.STATUS_NORMAL, target=target).order_by('-id')

django_blog_program/comment/forms.py
import mistune
from django import forms

from comment.models import Comment


class CommentForm(forms.ModelForm):
    nickname = forms.CharField(
        label='昵称',
        max_length=50,
        widget=forms.widgets.Input(
            attrs={'class': 'form-control', 'style': 'width: 60%;', 'placeholder': '昵称'}
        ),
    )
    email = forms.CharField(
        label='邮箱',
        max_length=50,
        widget=forms.widgets.Input(
            attrs={'class': 'form-control', 'style': 'width: 60%;', 'placeholder': '邮箱'}
        ),
    )
    website = forms.CharField(
        label='网站',
        max_length=100,
        widget=forms.widgets.Input(
            attrs={'class': 'form-control', 'style': 'width: 60%;', 'placeholder': '网站'}
        ),
    )
    content = forms.CharField(
        label='内容',
        max_length=500,
        widget=forms.widgets.Textarea(
            attrs={'class': 'form-control', 'rows': 5, 'cols': 60, 'placeholder': '请输入内容'}
        ),
    )

    def clean_content(self):
        content = self.cleaned_data.get('content')
        if len(content) < 10:
            raise forms.ValidationError('内容长度怎么能这么短呢')
        content = mistune.markdown(content)
        return content

    class Meta:
        model = Comment
        fields = ['nickname', 'email', 'website', 'content']

django_blog_program/comment/views.py
from django.contrib.messages.api import success
from django.shortcuts import redirect
from django.views.generic import TemplateView

from comment.forms import CommentForm


# Create your views here.


class CommentView(TemplateView):
    http_method_names = ['post']
    template_name = 'comment/result.html'

    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(request.POST)
        target = request.POST.get('target')

        if comment_form.is_valid():
            instance = comment_form.save(commit=False)
            instance.target = target
            instance.save()
            success = True
            return redirect( target)
        else:
            success = False

        content = {
            'success': success,
            'form': comment_form,
            'target': target
        }
        return self.render_to_response(content)

django_blog_program/django_blog_program/themes/bootstrap/templates/comment/block.html
<hr />
<div class="comment">
    <form action="/comment/" method="post" class="form-group">
        {% csrf_token %}
        <input type="hidden" name="target" value="{{ target }}">
        {{ comment_form }}
        <input type="submit" value="提交">
    </form>

    <ul class="list-group">
        {% for comment in comment_list %}
        <li class="list-group-item">
            <div class="nickname">
                <a href="{{ comment.website }}">{{ comment.nickname }}</a>
                <span class="comment-time">{{ comment.created_time }}</span>
            </div>
            <div class="comment-content">
                {% autoescape off %}
                {{ comment.content }}
                {% endautoescape %}
            </div>
        </li>
        {% endfor %}
    </ul>
</div>

django_blog_program/django_blog_program/themes/bootstrap/templates/comment/result.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>评论结果页</title>
    <style>
        body {
            background-color: #f5f5f5;
            text-align: center;
        }
        .result {
            text-align: center;
            width: 40%;
            margin: auto;
        }
        .errorlist {
            color: red;
        }
        ul li {
            list-style-type: none;
        }
    </style>
</head>
<body>
<div class="result">
    {% if success %}
    <h1>评论成功</h1>
    <a href="{{ target }}">返回</a>
    {% else %}
    <h1>评论失败</h1>
    <ul class="errorlist">
        {% for filed, message in form.errors.items %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    <a href="javascript:window.history.back();">返回</a>
    {% endif %}
</div>


</body>
</html>